name: "Terraform Valida Modulo"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    uses: "marlensouza/cicd_centralizado/.github/workflows/terraform_centralizado.yml@cicdcentralizado"
    with:
      aws_region: "us-east-1"
      working_directory: "./examples/private-bucket"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

